# Generated by Django 3.0.6 on 2020-05-12 16:27

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='event_dateTime',
        ),
        migrations.AddField(
            model_name='records',
            name='event_date',
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
